/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meinrechner;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Azad
 */
public class frmRechner extends javax.swing.JFrame {

    private double num1;

    /**
     * Creates new form frmRechner
     */
    public frmRechner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Alter Rechner");

        jButton1.setText("Jetzt rechnen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("wählen Sie Ihr Geburtsdatum aus!");

        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Schließen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txt1.setColumns(20);
        txt1.setRows(5);
        jScrollPane1.setViewportView(txt1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2)))
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          String q=String.valueOf(dc.getDate());
        
       if (q.equals("null")){JOptionPane.showMessageDialog(this, "das Geburtsdatum kann nicht leer sein!");}
       else{
       Scanner S = new Scanner(System.in);
        Date d = new Date();
        SimpleDateFormat yn = new SimpleDateFormat("yyyy");
        SimpleDateFormat mn = new SimpleDateFormat("MM");
        SimpleDateFormat dn = new SimpleDateFormat("dd");
        int jj = Integer.parseInt(yn.format(d));//jetztiger Jahr
        int jm = Integer.parseInt(mn.format(d));//jetztiger Monat
        int jt = Integer.parseInt(dn.format(d));//jetztiger Tag
        int gj, gm, gt, aj1 = 0, am1 = 0, at1 = 0,aj2, am2, at2;
        
        
       // System.out.println("Gib dein Geburtsjahr ein:");
        gj = Integer.parseInt(yn.format(dc.getDate()));
        //System.out.println("Gib dein Geburtsmonat ein:");
        gm = Integer.parseInt(mn.format(dc.getDate()));
        //System.out.println("Gib dein Geburtstag ein:");
        gt = Integer.parseInt(dn.format(dc.getDate()));
        /*aj1 = gy + 1;
        am1 = 12 - gm;//+1
        aj2 = jj - aj1;
        am2 = jm + am1;
        if (am2 == 12) {
            aj2 = aj2 + 1;
            am2 = 0;
        }
        System.out.println("Du bist " + aj2 + " Jahre und " + am2 + " Monate und alt");*/
        //Aktuelles Datum größer
        if (jm >= gm && jt >= gt) {
            aj1 = jj - gj;
            am1 = jm - gm;
            at1 = jt - gt;
        }//Aktuellar Monat größer aber Aktuellar Tag kleiner als die im Geburtsdatum
        else if (jm > gm && jt < gt) {
            aj1 = jj - gj;
            am1 = jm - (gm + 1);
            at1 = (30 - gt) + jt;
        }//Aktuellar Monat und Tag kleiner
        else if (jm < gm && jt < gt) {
            aj1 = jj - (gj + 1);
            am1 = (12 - (gm+1)+jm);
            at1 = (30 - gt) + jt;
        }//Aktuellar Monat kleiner aber Tag größer
        else if (jm < gm && jt > gt) {
            aj1 = jj - (gj + 1);
            am1 = (12 - gm) + jm;
            at1 = jt - gt;
        }//Aktuellar Monat==Geburtsmonat und akueller Tag kleiner Geburtstag
        else if (jm == gm && jt < gt) {
            aj1 = jj - (gj + 1);
            am1 = (12 - (gm + 1) + jm);
            at1 = (30 - gt) + jt;
        } else {
          //  System.out.println("Fehler getroffen!");
          JOptionPane.showMessageDialog(this, "Fehler getroffen!");
        }
       // System.out.println("Du bist " + aj1 + " Jahre und " + am1 + " Monate und " + at1 + " Tage alt");
        int ngt = 0;//der nächste Geburtstag
        int tank = 0;//die Summe von zwischen Monate
        int[] monate = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
        if (jj % 4 == 0) {
            monate[1] = 29;
        }//diese Jahr ist Schaltjahr
        if ((jj + 1) % 4 == 0) {
            monate[13] = 29;
        }//nächstes Jahr ist Schaltjahr
        if (jm == gm && jt <= gt) {
            ngt = gt - jt;
        }//im gleichen Monat hat man Geburtstag z.B nächste Woche
        else if (gm > jm) {
            for (int x = jm; x < gm - 1; x++) {
                tank += monate[x];
            }//im gleichen Jahr hat man Geburtstag z.B nächstes Monat
            ngt = (monate[jm - 1] - jt) + gt + tank;
        } else if (jm >= gm) {
            for (int x = jm; x < (gm + 12 - 1); x++) {
                tank += monate[x];
            }//im nächsten Jahr hat man Geburtstag
            ngt = (monate[jm - 1] - jt) + gt + tank;
        }
      // System.out.println("Du hast in " + ngt + " Tagen Geburtstag"+"\n-----------");
     //   System.out.print("wenn Sie nochmal rechnen möchten tippen Sie 'y':" + yn);
       // confirm=S.next().charAt(0);
        
    
        txt1.setText("Du bist " + aj1 + " Jahre und " + am1 + " Monate \n und " + at1 + " Tage alt"+"\n------------------"+"\nDu hast in " + ngt + " Tagen Geburtstag");
        
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmRechner().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt1;
    // End of variables declaration//GEN-END:variables
}
